### ISSUE TITLE
Фильтрация списка митапов по статусу

### ISSUE THREAD

**Issue by adaleorion** [devcomanda/easymeetup#55]
> Я хочу посмотреть список  всех активных митапов(на которые открыта регистрация), чтобы выбрать подходящий для себя

> Я хочу посмотреть список прошедших митапов

Добавить возможность отфильтровать список митапов по статусу. 
На данный момент в системе будет доступно три статуса для митапа:
- NEW - состояние когда митап только создан
- IN_PROGRESS -  состояние когда митап открыт для регистрации участников
- CLOSED - состояние когда митап еще не прошел, но уже закрыт для регистрации участников
- DONE - состояние когда митап уже прошел и закрыт для регистрации участников

`API GET /api/meetups?status=<some status>`

В случае когда статус не указан вернуть список митапов без фильтрации.

**Comment by FedosovMax** [comment]
Нужно сделать метод GET в контроллере, который принимает разные варианты статуса проекта и отдает в результате все проекты с запрашиваемым статусом. Или же это должны быть разные методы контроллера, которые будут отдавать каждый свой статус?

**Comment by adaleorion** [comment]
На мой взгляд, на данный момент можно использовать метод который уже существует и просто добавить возможность использования статусов
